In [1]:
import numpy as np

from experiments.utils.SimpleComparison import SimpleComparison
from hdimvis.algorithms.spring_force_algos.chalmers96_algo.Chalmers96 import Chalmers96
from hdimvis.visualise_layouts_and_metrics.plot import show_layout,show_generation_metrics
from hdimvis.algorithms.stochastic_ntet_algo.SNeD import SNeD
from hdimvis.create_low_d_layout.LayoutCreation import LayoutCreation
from hdimvis.data_fetchers.DataFetcher import DataFetcher
from hdimvis.visualise_layouts_and_metrics.plot import show_layout
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import KFold
from experiments.utils.get_kmeans_f1 import get_kmeans_f1
from experiments.utils.get_f1_for_best_k_with_knn import get_f1_for_best_k_with_knn
from experiments.utils.get_avg_classwise_f1 import get_avg_classwise_f1
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import f1_score
from pathlib import Path
from definitions import PROJECT_ROOT
import pickle
from scipy import stats
import matplotlib.pyplot as plt
from time import perf_counter
from  sklearn.manifold import SpectralEmbedding, MDS
from hdimvis.metrics.distance_measures.euclidian_and_manhattan import euclidean
import pandas as pd

In [7]:
names = ["coli20" ,"rna N3k", "globe"]

output_dir= (Path(PROJECT_ROOT).joinpath(
    Path(f"experiments/knnd/out/"))).resolve().absolute()


for name in names:
    print("#"*20)
    path_to_pickle = (Path(output_dir).joinpath(Path(f"results_arr_{name}.pickle"))).resolve()
    with open(path_to_pickle, 'rb') as file:
        arr = pickle.load(file)
    print(arr)
    print(name)
    print("#"*20)

    for i,metric in enumerate(["Stress", "k-means F1", "k", "kNN F1"]):
        print("#"*20)
        print(metric)
        print("#"*20)
        if i !=2:

            mean_knnd = np.mean(arr[0,:,i]).round(decimals=2)
            std_knnd = np.std(arr[0,:,i]).round(decimals=2)

            mean_no_knnd = np.mean(arr[1,:,i]).round(decimals=2)
            std_no_knnd = np.std(arr[1,:,i]).round(decimals=2)

            tstat, pvalue = stats.ttest_ind(arr[0,:,i].round(decimals=2), arr[1,:,i].round(decimals=2), equal_var=False, alternative='two-sided')
            result = np.format_float_scientific(pvalue, precision=2,min_digits=2)

            print(f"knnd :{mean_knnd} SD: {std_knnd}")
            print(f"no knnd :{mean_no_knnd} SD: {std_no_knnd}")

            print(f"test : {result}")

        else:
            print(f" knnd mean k - {np.mean(arr[0,:,i])}")
            print(f"no knnd mean k - {np.mean(arr[1,:,i])}")

####################
[[[0.2990778  0.39911184 2.         0.99799466]
  [0.29861204 0.40717008 2.         0.99799466]
  [0.29887219 0.38625162 2.         0.99799466]
  [0.29870815 0.36504202 2.         0.99799466]
  [0.29952764 0.40116283 2.         0.99799466]
  [0.29878353 0.39703238 2.         0.99799466]
  [0.2989009  0.39309869 2.         0.99799466]
  [0.29904146 0.3986545  2.         0.99799466]
  [0.29915209 0.36428098 2.         0.99799466]
  [0.29900802 0.37795816 2.         0.99799466]
  [0.29898915 0.39615893 2.         0.99799466]
  [0.29908132 0.40673867 2.         0.99799466]
  [0.29889016 0.40092443 2.         0.99799466]
  [0.30029439 0.36738319 2.         0.99799466]
  [0.2993692  0.37523211 2.         0.99799466]
  [0.29897623 0.41657431 2.         0.99799466]
  [0.29900919 0.38459065 2.         0.99799466]
  [0.2991839  0.38759261 2.         0.99799466]
  [0.29891476 0.40097465 2.         0.99799466]
  [0.29913905 0.41169255 2.         0.99799466]
  [0.29926483 0.392

C:\Users\Owner\AppData\Local\Temp\ipykernel_4784\308612165.py:28: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  tstat, pvalue = stats.ttest_ind(arr[0,:,i].round(decimals=2), arr[1,:,i].round(decimals=2), equal_var=False, alternative='two-sided')


In [2]:


knnd =  np.loadtxt(r"C:\Users\Owner\Desktop\2095736w\experiments\knnd\out\fashion_mnist_knnd.txt", usecols=(0,1,3))
print(knnd)



ValueError: could not convert string '0.80889892]' to float64 at row 10, column 4.