In [2]:
import numpy as np

from experiments.utils.SimpleComparison import SimpleComparison
from hdimvis.algorithms.spring_force_algos.chalmers96_algo.Chalmers96 import Chalmers96
from hdimvis.visualise_layouts_and_metrics.plot import show_layout,show_generation_metrics
from hdimvis.algorithms.stochastic_ntet_algo.SNeD import SNeD
from hdimvis.create_low_d_layout.LayoutCreation import LayoutCreation
from hdimvis.data_fetchers.DataFetcher import DataFetcher
from hdimvis.visualise_layouts_and_metrics.plot import show_layout
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import KFold
from experiments.utils.get_kmeans_f1 import get_kmeans_f1
from experiments.utils.get_f1_for_best_k_with_knn import get_f1_for_best_k_with_knn
from experiments.utils.get_avg_classwise_f1 import get_avg_classwise_f1
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import f1_score
from pathlib import Path
from definitions import PROJECT_ROOT
import pickle
from scipy import stats
import matplotlib.pyplot as plt
from time import perf_counter
from  sklearn.manifold import SpectralEmbedding, MDS
from hdimvis.metrics.distance_measures.euclidian_and_manhattan import euclidean
import pandas as pd

In [9]:
names = ["coli20" ,"rna N3k", "globe"]

output_dir= (Path(PROJECT_ROOT).joinpath(
    Path(f"experiments/knnd/out/"))).resolve().absolute()


for name in names:
    print("#"*20)
    path_to_pickle = (Path(output_dir).joinpath(Path(f"results_arr_{name}.pickle"))).resolve()
    with open(path_to_pickle, 'rb') as file:
        arr = pickle.load(file)
    print(arr)
    print(name)
    print("#"*20)

    for i,metric in enumerate(["Stress", "k-means F1", "k", "kNN F1"]):
        print(metric)
        if i !=2:

            mean_knnd = np.mean(arr[0,:,i])
            std_knnd = np.std(arr[0,:,i])

            mean_no_knnd = np.mean(arr[1,:,i])
            std_no_knnd = np.std(arr[1,:,i])

            tstat, pvalue = stats.ttest_ind(arr[0,:,i], arr[1,:,i], equal_var=False, alternative='two-sided')
            result = np.format_float_scientific(pvalue, precision=2,min_digits=2)

            print(f"knnd :{mean_knnd} SD: {std_knnd}")
            print(f"no knnd :{mean_no_knnd} SD: {std_no_knnd}")

            print(f"test : {result}")

        else:
            print(f" knnd mean k{np.mean(arr[0,:,i])}")
            print(f"no knnd mean k{np.mean(arr[1,:,i])}")

####################
[[[0.27153777 0.41212294 6.         0.80889892]
  [0.27153589 0.40430956 6.         0.80889892]
  [0.27159402 0.38492564 6.         0.80889892]
  [0.27169574 0.36697884 6.         0.80889892]
  [0.27142834 0.38003112 6.         0.80889892]
  [0.27152746 0.39388155 6.         0.80889892]
  [0.27151912 0.38082189 6.         0.80889892]
  [0.27146671 0.37591516 6.         0.80889892]
  [0.27175771 0.3866446  6.         0.80889892]
  [0.27167949 0.37764    6.         0.80889892]
  [0.27168342 0.38213904 6.         0.80889892]
  [0.27183923 0.38662258 6.         0.80889892]
  [0.27142518 0.385137   6.         0.80889892]
  [0.27181955 0.38700944 6.         0.80889892]
  [0.2715723  0.38297834 6.         0.80889892]]

 [[0.27438131 0.39209848 6.         0.80889892]
  [0.27468774 0.38000491 6.         0.80889892]
  [0.27448406 0.36312378 6.         0.80889892]
  [0.27472201 0.37875117 6.         0.80889892]
  [0.27473613 0.39059888 6.         0.80889892]
  [0.27458695 0.3

C:\Users\Owner\AppData\Local\Temp\ipykernel_16224\1093986105.py:26: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  tstat, pvalue = stats.ttest_ind(arr[0,:,i], arr[1,:,i], equal_var=False, alternative='two-sided')
