In [9]:
from sklearn.manifold import TSNE
import numpy as np
from hdimvis.data_fetchers.DataFetcher import DataFetcher
from time import perf_counter
from pathlib import Path
import pickle



In [12]:
dataset = DataFetcher.fetch_data('globe', size= 10000)

####################
Fetching the "globe" dataset
####################
Dataset loaded
Dataset shape: (5002, 3)
####################


In [13]:
from definitions import PROJECT_ROOT

perplex_values = np.linspace(10, 5000, 10)
num_repeats = 3
results = np.zeros((10, 4))

for i, value in enumerate(perplex_values):
    print(i)
    results[i,0] = value
    for j in range(1, num_repeats+1):
        print(j)
        start= perf_counter()
        tsne_layout = TSNE(n_components=2, perplexity=value).fit_transform(dataset.data)
        results[i,j] = perf_counter()

print(results)
output_dir= (Path(PROJECT_ROOT).joinpath(
    Path(f"experiments/globe_and_tsne_umap_compare/out/"))).resolve().absolute()

path_to_pickle = (Path(output_dir).joinpath(Path(f"tsne_perplex.pickle"))).resolve()
with open(path_to_pickle, 'wb') as pickle_out:
    pickle.dump(results, pickle_out)

0
1
2
3
1
1
2
3
2
1
2
3
3
1
2
3
4
1
2
3
5
1
2
3
6
1
2
3
7
1
2
3
8
1
2
3
9
1
2
3
[[1.00000000e+01 6.60276995e+04 6.60361094e+04 6.60444785e+04]
 [2.86666667e+02 6.60774264e+04 6.61109606e+04 6.61444315e+04]
 [5.63333333e+02 6.62049375e+04 6.62680735e+04 6.63279230e+04]
 [8.40000000e+02 6.64147799e+04 6.64990872e+04 6.65843561e+04]
 [1.11666667e+03 6.66856714e+04 6.67879826e+04 6.68938852e+04]
 [1.39333333e+03 6.70105387e+04 6.71281048e+04 6.72471061e+04]
 [1.67000000e+03 6.73188088e+04 6.73903952e+04 6.74633122e+04]
 [1.94666667e+03 6.75584574e+04 6.76540663e+04 6.77539394e+04]
 [2.22333333e+03 6.78814844e+04 6.80107440e+04 6.81402610e+04]
 [2.50000000e+03 6.82113738e+04 6.82835450e+04 6.83579524e+04]]
